name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions
      with:
        github_access_token: ${{ secrets.USER_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: npm run build # The build environment for the app. please look configurations in your angular.json
        base_href: https://san2beerelli.github.io/loh/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: master # The branch the action should deploy to.
        build_folder: build # The folder where your project is supposed to be after running ng build by the action.

